server:
  port: 80
  servlet:
    context-path: /community
spring:
  datasource:
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong

  thymeleaf:
    cache: false



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ancientmoon.newcommunity.entity

  configuration:
    map-underscore-to-camel-case: true

#logging:
#  level:
#    com.ancientmoon.newcommunity: debug
#  file:
#    path: /Users/huliheng/IdeaProjects/NewCommunity/src/main/java/com/ancientmoon/newcommunity/log
