server:
  port: 80
  servlet:
    context-path: /community
spring:
  datasource:
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong

  thymeleaf:
    cache: false

  #Mail配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 821786679@qq.com
    password: vgnpxmsizowabcbh
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    protocol: smtps




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ancientmoon.newcommunity.entity

  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true



#logging:
#  level:
#    com.ancientmoon.newcommunity: debug
#  file:
#    path: /Users/huliheng/IdeaProjects/NewCommunity/src/main/java/com/ancientmoon/newcommunity/log

#community

community:
  path:
    domain: http://localhost:80
    upload: /Users/huliheng/IdeaProjects/NewCommunity/src/main/resources/upload